- name: Print catalogue
  debug:
    msg: catalogue

  yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y

  yum module enable redis:remi-6.2 -y

  yum install redis -y

  systemctl enable redis
  systemctl start redis

- name: Installing nginx
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: yes
- name: Install the latest version of Apache
  ansible.builtin.dnf:
    name: "@redis:remi-6.2"
    state: installed

- name: Update listen address from 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restart redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes